"""
Komga Metadata Exporter

Exports Komga series/book metadata to portable file formats:
- Mylar3 series.json (for Komga native import)
- ComicInfo.xml (for embedding in cbz/cbr)
- eze info.json (for eze reader)

Usage:
    python metadata_exporter.py                    # Export all series and books
    python metadata_exporter.py --series-id ID     # Export single series
    python metadata_exporter.py --book-id ID       # Export single book
    python metadata_exporter.py --force            # Force overwrite existing files
    python metadata_exporter.py --comicinfo --eze  # Also export book-level formats
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime
from xml.etree.ElementTree import Element, SubElement, tostring
import xml.dom.minidom


# ---------------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------------

def sanitize_filename(name, max_length=200):
    """Sanitize a string for safe use as a file or directory name.

    Replaces illegal characters, strips leading/trailing spaces and dots,
    collapses consecutive underscores, and truncates to *max_length*.
    """
    if not name:
        return 'untitled'
    name = re.sub(r'[<>:"/\\|?*]', '_', name)
    name = name.strip(' .')
    name = re.sub(r'__+', '_', name)
    if len(name) > max_length:
        name = name[:max_length].rstrip('_. ')
    return name or 'untitled'


# ---------------------------------------------------------------------------
# ComicInfo.xml generator
# ---------------------------------------------------------------------------

def generate_comic_info(book_json):
    """Build a ComicInfo.xml Element tree from a Komga *book* JSON response."""
    comic_info = Element('ComicInfo')
    comic_info.set('xmlns:xsd', 'http://www.w3.org/2001/XMLSchema')
    comic_info.set('xmlns:xsi', 'http://www.w3.org/2001/XMLSchema-instance')

    metadata = book_json.get('metadata', {})
    title = metadata.get('title') or book_json.get('name', '')

    # Title
    title_elem = SubElement(comic_info, 'Title')
    title_elem.text = title

    # Notes
    notes_elem = SubElement(comic_info, 'Notes')
    notes_elem.text = f'Generated by BangumiKomga on {datetime.now().isoformat()}'

    # Release date → Year / Month / Day
    release_date_str = metadata.get('releaseDate')
    if release_date_str:
        try:
            release_date = datetime.strptime(release_date_str, '%Y-%m-%d')
            for tag, val in [('Year', release_date.year),
                             ('Month', release_date.month),
                             ('Day', release_date.day)]:
                elem = SubElement(comic_info, tag)
                elem.text = str(val)
        except (ValueError, TypeError):
            pass

    # Writer — all authors comma-separated
    authors = metadata.get('authors', [])
    if authors:
        writer_elem = SubElement(comic_info, 'Writer')
        writer_elem.text = ', '.join(a['name'] for a in authors if a.get('name'))

    # Tags
    tags = metadata.get('tags', [])
    if tags:
        tags_elem = SubElement(comic_info, 'Tags')
        tags_elem.text = ', '.join(tags)

    # Web — first link
    links = metadata.get('links', [])
    if links:
        web_elem = SubElement(comic_info, 'Web')
        web_elem.text = links[0].get('url', '')

    # PageCount
    media = book_json.get('media', {})
    page_count_elem = SubElement(comic_info, 'PageCount')
    page_count_elem.text = str(media.get('pagesCount', 0))

    # LanguageISO
    language_elem = SubElement(comic_info, 'LanguageISO')
    language_elem.text = metadata.get('language') or 'zh'

    # Format
    format_elem = SubElement(comic_info, 'Format')
    format_elem.text = 'Digital'

    # Manga
    manga_elem = SubElement(comic_info, 'Manga')
    manga_elem.text = 'YesAndRightToLeft'

    # Pages element (page numbers only — per-page dimensions unavailable in
    # Komga's standard book response)
    pages_elem = SubElement(comic_info, 'Pages')
    for i in range(1, media.get('pagesCount', 0) + 1):
        page_elem = SubElement(pages_elem, 'Page')
        page_elem.set('Image', str(i))

    return comic_info


def prettify_comic_info(elem):
    """Pretty-print an XML Element to a UTF-8 string."""
    rough_string = tostring(elem, 'utf-8')
    reparsed = xml.dom.minidom.parseString(rough_string)
    return reparsed.toprettyxml(indent="  ")


# ---------------------------------------------------------------------------
# eze info.json generator
# ---------------------------------------------------------------------------

def generate_eze_info(book_json):
    """Build an eze-compatible ``info.json`` dict from a Komga *book* JSON
    response."""
    metadata = book_json.get('metadata', {})

    # Release date
    release_date_str = metadata.get('releaseDate')
    if release_date_str:
        try:
            release_date = datetime.strptime(release_date_str, '%Y-%m-%d')
            upload_date = [release_date.year, release_date.month, release_date.day]
        except (ValueError, TypeError):
            upload_date = [1970, 1, 1]
    else:
        upload_date = [1970, 1, 1]

    links = metadata.get('links', [])

    # Tags
    tags_list = metadata.get('tags', [])
    is_translated = any(
        'translated' in (t.lower() if isinstance(t, str) else '')
        for t in tags_list
    )

    tags = {
        "tag": tags_list,
        "language": [metadata['language']] if metadata.get('language') else [],
        "category": ["manga"],
        "artist": [a['name'] for a in metadata.get('authors', []) if a.get('name')],
        "group": [metadata['publisher']] if metadata.get('publisher') else [],
    }

    # Source — Komga links + Bangumi links
    source_links = [
        {"name": link.get('label', ''), "url": link.get('url', '')}
        for link in links
    ]

    return {
        "gallery_info": {
            "title": metadata.get('title') or book_json.get('name', ''),
            "title_original": book_json.get('name', ''),
            "link": links,
            "category": "manga",
            "tags": tags,
            "language": metadata.get('language', 'zh'),
            "translated": is_translated,
            "upload_date": upload_date,
            "source": {
                "links": source_links,
            },
        }
    }


# ---------------------------------------------------------------------------
# Mylar3 series.json generator
# ---------------------------------------------------------------------------

def generate_mylar_info(series_json, base_url=""):
    """Build a Mylar3-compatible ``series.json`` dict from a Komga *series*
    JSON response.

    *base_url* is prepended to ``comic_image`` to produce an absolute URL
    (e.g. ``https://komga.example.com``).
    """
    metadata = series_json.get('metadata', {})
    books_metadata = series_json.get('booksMetadata', {})

    series_title = metadata.get('title') or series_json.get('name', '')
    publisher = metadata.get('publisher') or ''

    # Year — try booksMetadata.releaseDate first, then metadata.releaseDate
    year = 1970
    release_date_str = (books_metadata.get('releaseDate') or
                        metadata.get('releaseDate'))
    if release_date_str:
        if isinstance(release_date_str, str) and len(release_date_str) >= 4:
            try:
                year = int(release_date_str[:4])
            except (ValueError, TypeError):
                pass
        elif isinstance(release_date_str, (int, float)):
            year = int(release_date_str)

    # Description — multi-source fallback
    description = (metadata.get('summary') or
                   books_metadata.get('summary') or
                   metadata.get('description') or '')
    if not isinstance(description, str):
        description = ''

    # Status mapping
    komga_status = (metadata.get('status') or '').upper()
    mylar_status = {
        "ONGOING": "Continuing",
        "HIATUS": "Continuing",
        "ABANDONED": "Continuing",
        "ENDED": "Ended",
    }.get(komga_status, "Continuing")

    total_issues = int(series_json.get('booksCount', 0))

    # Age rating normalisation
    def _normalize_age_rating(value):
        if value is None:
            return None
        if isinstance(value, str):
            value = value.strip().lower()
            if value.isdigit():
                value = int(value)
            else:
                return None
        if value <= 0:
            return "All"
        if value < 12:
            return "9+"
        if value < 15:
            return "12+"
        if value < 17:
            return "15+"
        if value < 18:
            return "17+"
        return "Adult"

    age_rating = _normalize_age_rating(metadata.get('ageRating'))

    # Book type normalisation
    raw_booktype = (metadata.get('bookType') or '').strip().lower()
    _type_map = {
        'trade': 'TPB', 'tpb': 'TPB',
        'graphic': 'GN',
        'hardcover': 'HC', 'hc': 'HC',
        'magazine': 'Magazine',
        'digital': 'Digital',
    }
    normalized_booktype = 'Print'
    for key, val in _type_map.items():
        if key in raw_booktype:
            normalized_booktype = val
            break

    collects = metadata.get('collects')
    if collects is None and normalized_booktype in ('TPB', 'GN', 'HC'):
        collects = []
    if collects:
        normalized_booktype = 'TPB'

    # Thumbnail URL
    series_id = series_json.get('id', '')
    if base_url:
        comic_image = f"{base_url.rstrip('/')}/api/v1/series/{series_id}/thumbnail"
    else:
        comic_image = f"/api/v1/series/{series_id}/thumbnail"

    return {
        "version": "1.0.2",
        "metadata": {
            "type": "comicSeries",
            "publisher": publisher,
            "imprint": metadata.get('imprint'),
            "name": series_title,
            "comicid": series_id,
            "year": year,
            "description_text": description.strip(),
            "description_formatted": None,
            "volume": metadata.get('volume'),
            "booktype": normalized_booktype,
            "age_rating": age_rating,
            "collects": collects,
            "comic_image": comic_image,
            "total_issues": total_issues,
            "publication_run": metadata.get('publicationRun') or '',
            "status": mylar_status,
            "language": metadata.get('language'),
            "readingDirection": metadata.get('readingDirection'),
            "releaseDate": str(year),
            "authors": (books_metadata.get('authors') or
                        metadata.get('authors') or []),
            "links": metadata.get('links') or [],
            "alternateTitles": metadata.get('alternateTitles') or [],
            "genres": metadata.get('genres') or [],
            "tags": (metadata.get('tags') or
                     books_metadata.get('tags') or
                     series_json.get('tags') or []),
        }
    }


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

def get_output_path(output_dir, series_name, series_id,
                    book_name=None, book_id=None):
    """Return the output path for a series or book.

    ``export_dir / SeriesName_SeriesID [/ BookName_BookID]``
    """
    safe_series = sanitize_filename(f"{series_name}_{series_id}")
    series_dir = os.path.join(output_dir, safe_series)

    if book_name and book_id:
        safe_book = sanitize_filename(f"{book_name}_{book_id}")
        return os.path.join(series_dir, safe_book)
    return series_dir


# ---------------------------------------------------------------------------
# Export logic
# ---------------------------------------------------------------------------

def export_series(komga, series_id, output_dir, base_url, force=False,
                  export_series_json=True, export_comicinfo=False,
                  export_eze=False):
    """Export all metadata for a single series and its contained books."""
    series_data = komga.get_specific_series(series_id)
    if not series_data:
        print(f"Error: Could not fetch series {series_id}")
        return

    series_name = (series_data.get('metadata', {}).get('title') or
                   series_data.get('name', series_id))
    series_dir = get_output_path(output_dir, series_name, series_id)
    os.makedirs(series_dir, exist_ok=True)

    # --- series.json ---
    if export_series_json:
        series_file = os.path.join(series_dir, 'series.json')
        if force or not os.path.exists(series_file):
            mylar_data = generate_mylar_info(series_data, base_url)
            with open(series_file, 'w', encoding='utf-8') as f:
                json.dump(mylar_data, f, ensure_ascii=False, indent=2)
            print(f"  ✓ series.json → {series_file}")

    # --- books ---
    if export_comicinfo or export_eze:
        books_resp = komga.get_series_books(series_id)
        books = books_resp.get('content', []) if isinstance(books_resp, dict) else books_resp

        for book in books:
            book_id = book.get('id', '')
            book_json = komga.get_book_metadata(book_id)
            if not book_json:
                continue

            book_name = (book_json.get('metadata', {}).get('title') or
                         book_json.get('name', book_id))
            book_dir = get_output_path(output_dir, series_name, series_id,
                                       book_name, book_id)
            os.makedirs(book_dir, exist_ok=True)

            if export_comicinfo:
                cf = os.path.join(book_dir, 'ComicInfo.xml')
                if force or not os.path.exists(cf):
                    xml_str = prettify_comic_info(generate_comic_info(book_json))
                    with open(cf, 'w', encoding='utf-8') as f:
                        f.write(xml_str)
                    print(f"    ✓ ComicInfo.xml → {cf}")

            if export_eze:
                ef = os.path.join(book_dir, 'info.json')
                if force or not os.path.exists(ef):
                    eze_data = generate_eze_info(book_json)
                    with open(ef, 'w', encoding='utf-8') as f:
                        json.dump(eze_data, f, ensure_ascii=False, indent=2)
                    print(f"    ✓ info.json → {ef}")


def export_single_book(komga, book_id, output_dir, base_url, force=False,
                       export_comicinfo=True, export_eze=True):
    """Export metadata for a single book (no series.json)."""
    book_json = komga.get_book_metadata(book_id)
    if not book_json:
        print(f"Error: Could not fetch book {book_id}")
        return

    series_id = book_json.get('seriesId', 'unknown')
    series_title = book_json.get('seriesTitle', 'unknown')
    book_name = (book_json.get('metadata', {}).get('title') or
                 book_json.get('name', book_id))

    book_dir = get_output_path(output_dir, series_title, series_id,
                               book_name, book_id)
    os.makedirs(book_dir, exist_ok=True)

    if export_comicinfo:
        cf = os.path.join(book_dir, 'ComicInfo.xml')
        if force or not os.path.exists(cf):
            xml_str = prettify_comic_info(generate_comic_info(book_json))
            with open(cf, 'w', encoding='utf-8') as f:
                f.write(xml_str)
            print(f"✓ ComicInfo.xml → {cf}")

    if export_eze:
        ef = os.path.join(book_dir, 'info.json')
        if force or not os.path.exists(ef):
            eze_data = generate_eze_info(book_json)
            with open(ef, 'w', encoding='utf-8') as f:
                json.dump(eze_data, f, ensure_ascii=False, indent=2)
            print(f"✓ info.json → {ef}")


def export_all(komga, output_dir, base_url, force=False,
               export_series_json=True, export_comicinfo=False,
               export_eze=False):
    """Export every series (and optionally every book) in Komga."""
    all_series = komga.get_all_series()
    series_list = all_series.get('content', []) if isinstance(all_series, dict) else all_series

    if not series_list:
        print("No series found in Komga.")
        return

    print(f"Found {len(series_list)} series to export.\n")
    for i, series in enumerate(series_list, 1):
        sid = series.get('id', '')
        sname = series.get('name', sid)
        print(f"[{i}/{len(series_list)}] {sname}")
        export_series(komga, sid, output_dir, base_url, force,
                      export_series_json, export_comicinfo, export_eze)

    print("\nExport complete.")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description='Export Komga metadata to portable file formats.'
    )
    parser.add_argument('--series-id', type=str,
                        help='Export a single series by ID')
    parser.add_argument('--book-id', type=str,
                        help='Export a single book by ID')
    parser.add_argument('--force', action='store_true',
                        help='Force overwrite existing files')
    parser.add_argument('--output-dir', type=str, default=None,
                        help='Override export directory (default from config)')
    parser.add_argument('--no-series-json', action='store_true',
                        help='Skip series.json export')
    parser.add_argument('--comicinfo', action='store_true',
                        help='Enable ComicInfo.xml export')
    parser.add_argument('--eze', action='store_true',
                        help='Enable eze info.json export')

    args = parser.parse_args()

    # Delayed imports — avoid circular dependency during test discovery
    from tools.env import InitEnv
    from config.config import KOMGA_BASE_URL
    import config.config as cfg

    env = InitEnv()
    komga = env.komga

    output_dir = args.output_dir or getattr(cfg, 'EXPORT_DIR', './data/exported_info/')
    os.makedirs(output_dir, exist_ok=True)

    export_sj = (getattr(cfg, 'EXPORT_SERIES_JSON', True)
                 and not args.no_series_json)
    export_ci = (getattr(cfg, 'EXPORT_COMICINFO_XML', False)
                 or args.comicinfo)
    export_ei = (getattr(cfg, 'EXPORT_EZE_INFO_JSON', False)
                 or args.eze)

    if args.series_id:
        export_series(komga, args.series_id, output_dir, KOMGA_BASE_URL,
                      args.force, export_sj, export_ci, export_ei)
    elif args.book_id:
        export_single_book(komga, args.book_id, output_dir, KOMGA_BASE_URL,
                           args.force, export_ci, export_ei)
    else:
        export_all(komga, output_dir, KOMGA_BASE_URL, args.force,
                   export_sj, export_ci, export_ei)


if __name__ == '__main__':
    main()
