import json
import os
import sys
import unittest
from xml.etree import ElementTree as ET

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from metadata_exporter import (
    sanitize_filename,
    generate_comic_info,
    prettify_comic_info,
    generate_eze_info,
    generate_mylar_info,
    get_output_path,
)

FIXTURES_DIR = os.path.join(os.path.dirname(__file__), 'fixtures')


def load_fixture(name):
    with open(os.path.join(FIXTURES_DIR, name), 'r', encoding='utf-8') as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# sanitize_filename
# ---------------------------------------------------------------------------

class TestSanitizeFilename(unittest.TestCase):
    def test_illegal_chars_replaced(self):
        self.assertEqual(sanitize_filename('test:file'), 'test_file')
        self.assertEqual(sanitize_filename('a<b>c"d/e\\f|g?h*i'), 'a_b_c_d_e_f_g_h_i')

    def test_strips_leading_trailing_spaces_and_dots(self):
        self.assertEqual(sanitize_filename('  hello  '), 'hello')
        self.assertEqual(sanitize_filename('...test...'), 'test')
        self.assertEqual(sanitize_filename(' .mixed. '), 'mixed')

    def test_collapse_consecutive_underscores(self):
        self.assertEqual(sanitize_filename('a__b___c'), 'a_b_c')

    def test_truncation(self):
        long_name = 'x' * 300
        result = sanitize_filename(long_name, max_length=200)
        self.assertEqual(len(result), 200)
        self.assertFalse(result.endswith('_'))

    def test_none_returns_untitled(self):
        self.assertEqual(sanitize_filename(None), 'untitled')

    def test_empty_returns_untitled(self):
        self.assertEqual(sanitize_filename(''), 'untitled')

    def test_chinese_chars_preserved(self):
        self.assertEqual(sanitize_filename('三月的狮子'), '三月的狮子')

    def test_underscore_only_after_cleanup(self):
        self.assertEqual(sanitize_filename('***'), '_')


# ---------------------------------------------------------------------------
# generate_comic_info
# ---------------------------------------------------------------------------

class TestGenerateComicInfo(unittest.TestCase):
    def setUp(self):
        self.book = load_fixture('book_sample.json')

    def test_title(self):
        elem = generate_comic_info(self.book)
        title = elem.find('Title')
        self.assertIsNotNone(title)
        self.assertEqual(title.text, '三月的狮子 第1卷')

    def test_notes_present(self):
        elem = generate_comic_info(self.book)
        notes = elem.find('Notes')
        self.assertIsNotNone(notes)
        self.assertIn('Generated by BangumiKomga', notes.text)

    def test_writer_multiple_authors(self):
        elem = generate_comic_info(self.book)
        writer = elem.find('Writer')
        self.assertIsNotNone(writer)
        self.assertIn('羽海野チカ', writer.text)

    def test_tags_comma_separated(self):
        elem = generate_comic_info(self.book)
        tags = elem.find('Tags')
        self.assertIsNotNone(tags)
        self.assertIn('治愈', tags.text)

    def test_page_count(self):
        elem = generate_comic_info(self.book)
        pc = elem.find('PageCount')
        self.assertIsNotNone(pc)
        self.assertEqual(pc.text, '200')

    def test_web_link_first_only(self):
        elem = generate_comic_info(self.book)
        web = elem.find('Web')
        self.assertIsNotNone(web)
        self.assertEqual(web.text, 'https://bgm.tv/subject/1902')

    def test_language_fallback_to_zh(self):
        elem = generate_comic_info(self.book)
        lang = elem.find('LanguageISO')
        self.assertIsNotNone(lang)
        self.assertEqual(lang.text, 'zh')

    def test_format_digital(self):
        elem = generate_comic_info(self.book)
        fmt = elem.find('Format')
        self.assertIsNotNone(fmt)
        self.assertEqual(fmt.text, 'Digital')

    def test_manga_right_to_left(self):
        elem = generate_comic_info(self.book)
        manga = elem.find('Manga')
        self.assertIsNotNone(manga)
        self.assertEqual(manga.text, 'YesAndRightToLeft')

    def test_pages_element_count(self):
        elem = generate_comic_info(self.book)
        pages = elem.find('Pages')
        self.assertIsNotNone(pages)
        page_elems = pages.findall('Page')
        self.assertEqual(len(page_elems), 200)
        self.assertEqual(page_elems[0].get('Image'), '1')

    def test_no_authors(self):
        book = json.loads(json.dumps(self.book))
        book['metadata']['authors'] = []
        elem = generate_comic_info(book)
        writer = elem.find('Writer')
        self.assertIsNone(writer)

    def test_no_release_date(self):
        book = json.loads(json.dumps(self.book))
        book['metadata']['releaseDate'] = None
        elem = generate_comic_info(book)
        year = elem.find('Year')
        self.assertIsNone(year)

    def test_title_falls_back_to_name(self):
        book = json.loads(json.dumps(self.book))
        book['metadata']['title'] = ''
        elem = generate_comic_info(book)
        title = elem.find('Title')
        self.assertEqual(title.text, '三月的狮子 第01卷.cbz')

    def test_prettify_produces_valid_xml(self):
        elem = generate_comic_info(self.book)
        xml_str = prettify_comic_info(elem)
        self.assertIn('<?xml', xml_str)
        self.assertIn('<ComicInfo', xml_str)
        # Should parse back
        ET.fromstring(xml_str.encode('utf-8'))

    def test_no_tags(self):
        book = json.loads(json.dumps(self.book))
        book['metadata']['tags'] = []
        elem = generate_comic_info(book)
        self.assertIsNone(elem.find('Tags'))

    def test_no_links(self):
        book = json.loads(json.dumps(self.book))
        book['metadata']['links'] = []
        elem = generate_comic_info(book)
        self.assertIsNone(elem.find('Web'))


# ---------------------------------------------------------------------------
# generate_eze_info
# ---------------------------------------------------------------------------

class TestGenerateEzeInfo(unittest.TestCase):
    def setUp(self):
        self.book = load_fixture('book_sample.json')

    def test_title(self):
        info = generate_eze_info(self.book)
        self.assertEqual(info['gallery_info']['title'], '三月的狮子 第1卷')

    def test_title_original(self):
        info = generate_eze_info(self.book)
        self.assertEqual(info['gallery_info']['title_original'], '三月的狮子 第01卷.cbz')

    def test_tags(self):
        info = generate_eze_info(self.book)
        tags = info['gallery_info']['tags']
        self.assertIn('治愈', tags['tag'])
        self.assertIn('translated', tags['tag'])

    def test_artists(self):
        info = generate_eze_info(self.book)
        self.assertIn('羽海野チカ', info['gallery_info']['tags']['artist'])

    def test_translated_detection_true(self):
        info = generate_eze_info(self.book)
        self.assertTrue(info['gallery_info']['translated'])

    def test_translated_detection_false(self):
        book = json.loads(json.dumps(self.book))
        book['metadata']['tags'] = ['治愈', '将棋']  # no "translated"
        info = generate_eze_info(book)
        self.assertFalse(info['gallery_info']['translated'])

    def test_source_links(self):
        info = generate_eze_info(self.book)
        sources = info['gallery_info']['source']['links']
        self.assertTrue(any(
            'bgm.tv' in s.get('url', '').lower() for s in sources
        ))

    def test_upload_date(self):
        info = generate_eze_info(self.book)
        self.assertEqual(info['gallery_info']['upload_date'], [2008, 2, 22])

    def test_upload_date_fallback(self):
        book = json.loads(json.dumps(self.book))
        book['metadata']['releaseDate'] = None
        info = generate_eze_info(book)
        self.assertEqual(info['gallery_info']['upload_date'], [1970, 1, 1])

    def test_category_manga(self):
        info = generate_eze_info(self.book)
        self.assertEqual(info['gallery_info']['category'], 'manga')
        self.assertEqual(info['gallery_info']['tags']['category'], ['manga'])

    def test_no_authors(self):
        book = json.loads(json.dumps(self.book))
        book['metadata']['authors'] = []
        info = generate_eze_info(book)
        self.assertEqual(info['gallery_info']['tags']['artist'], [])

    def test_publisher_in_group(self):
        book = json.loads(json.dumps(self.book))
        book['metadata']['publisher'] = '白泉社'
        info = generate_eze_info(book)
        self.assertIn('白泉社', info['gallery_info']['tags']['group'])


# ---------------------------------------------------------------------------
# generate_mylar_info
# ---------------------------------------------------------------------------

class TestGenerateMylarInfo(unittest.TestCase):
    def setUp(self):
        self.series = load_fixture('series_sample.json')

    def test_publisher(self):
        info = generate_mylar_info(self.series)
        self.assertEqual(info['metadata']['publisher'], '白泉社')

    def test_name(self):
        info = generate_mylar_info(self.series)
        self.assertEqual(info['metadata']['name'], '3月的狮子')

    def test_comicid(self):
        info = generate_mylar_info(self.series)
        self.assertEqual(info['metadata']['comicid'], '0JR3CFZ42GMGT')

    def test_version(self):
        info = generate_mylar_info(self.series)
        self.assertEqual(info['version'], '1.0.2')

    def test_type_comic_series(self):
        info = generate_mylar_info(self.series)
        self.assertEqual(info['metadata']['type'], 'comicSeries')

    def test_status_ongoing_maps_to_continuing(self):
        info = generate_mylar_info(self.series)
        self.assertEqual(info['metadata']['status'], 'Continuing')

    def test_status_ended(self):
        s = json.loads(json.dumps(self.series))
        s['metadata']['status'] = 'ENDED'
        info = generate_mylar_info(s)
        self.assertEqual(info['metadata']['status'], 'Ended')

    def test_status_hiatus_maps_to_continuing(self):
        s = json.loads(json.dumps(self.series))
        s['metadata']['status'] = 'HIATUS'
        info = generate_mylar_info(s)
        self.assertEqual(info['metadata']['status'], 'Continuing')

    def test_status_unknown_defaults_to_continuing(self):
        s = json.loads(json.dumps(self.series))
        s['metadata']['status'] = ''
        info = generate_mylar_info(s)
        self.assertEqual(info['metadata']['status'], 'Continuing')

    def test_total_issues(self):
        info = generate_mylar_info(self.series)
        self.assertEqual(info['metadata']['total_issues'], 17)

    def test_age_rating_15(self):
        info = generate_mylar_info(self.series)
        self.assertEqual(info['metadata']['age_rating'], '15+')

    def test_age_rating_adult(self):
        s = json.loads(json.dumps(self.series))
        s['metadata']['ageRating'] = 18
        info = generate_mylar_info(s)
        self.assertEqual(info['metadata']['age_rating'], 'Adult')

    def test_age_rating_all(self):
        s = json.loads(json.dumps(self.series))
        s['metadata']['ageRating'] = 0
        info = generate_mylar_info(s)
        self.assertEqual(info['metadata']['age_rating'], 'All')

    def test_age_rating_none(self):
        s = json.loads(json.dumps(self.series))
        s['metadata']['ageRating'] = None
        info = generate_mylar_info(s)
        self.assertIsNone(info['metadata']['age_rating'])

    def test_comic_image_with_base_url(self):
        info = generate_mylar_info(self.series, base_url='https://komga.example.com')
        self.assertTrue(info['metadata']['comic_image'].startswith('https://'))
        self.assertIn('/api/v1/series/0JR3CFZ42GMGT/thumbnail',
                      info['metadata']['comic_image'])

    def test_comic_image_without_base_url(self):
        info = generate_mylar_info(self.series)
        self.assertEqual(info['metadata']['comic_image'],
                         '/api/v1/series/0JR3CFZ42GMGT/thumbnail')

    def test_tags(self):
        info = generate_mylar_info(self.series)
        self.assertIn('治愈', info['metadata']['tags'])
        self.assertIn('将棋', info['metadata']['tags'])

    def test_year_from_books_metadata(self):
        info = generate_mylar_info(self.series)
        self.assertEqual(info['metadata']['year'], 2008)

    def test_year_fallback_to_1970(self):
        s = json.loads(json.dumps(self.series))
        s['booksMetadata']['releaseDate'] = None
        s['metadata']['releaseDate'] = None
        info = generate_mylar_info(s)
        self.assertEqual(info['metadata']['year'], 1970)

    def test_release_date_field(self):
        info = generate_mylar_info(self.series)
        self.assertEqual(info['metadata']['releaseDate'], '2008')

    def test_links(self):
        info = generate_mylar_info(self.series)
        self.assertTrue(any(
            'bgm.tv' in l.get('url', '') for l in info['metadata']['links']
        ))

    def test_alternate_titles(self):
        info = generate_mylar_info(self.series)
        titles = [t['title'] for t in info['metadata']['alternateTitles']]
        self.assertIn('3月のライオン', titles)

    def test_genres(self):
        info = generate_mylar_info(self.series)
        self.assertIn('治愈', info['metadata']['genres'])

    def test_booktype_print_default(self):
        info = generate_mylar_info(self.series)
        self.assertEqual(info['metadata']['booktype'], 'Print')

    def test_booktype_tpb(self):
        s = json.loads(json.dumps(self.series))
        s['metadata']['bookType'] = 'TPB'
        info = generate_mylar_info(s)
        self.assertEqual(info['metadata']['booktype'], 'TPB')

    def test_booktype_digital(self):
        s = json.loads(json.dumps(self.series))
        s['metadata']['bookType'] = 'Digital'
        info = generate_mylar_info(s)
        self.assertEqual(info['metadata']['booktype'], 'Digital')

    def test_language(self):
        info = generate_mylar_info(self.series)
        self.assertEqual(info['metadata']['language'], 'zh')

    def test_reading_direction(self):
        info = generate_mylar_info(self.series)
        self.assertEqual(info['metadata']['readingDirection'], 'RIGHT_TO_LEFT')

    def test_description(self):
        info = generate_mylar_info(self.series)
        self.assertIn('桐山零', info['metadata']['description_text'])


# ---------------------------------------------------------------------------
# get_output_path
# ---------------------------------------------------------------------------

class TestGetOutputPath(unittest.TestCase):
    def test_series_path(self):
        path = get_output_path('/export', '三月的狮子', 'ABC123')
        self.assertTrue(path.startswith('/export'))
        self.assertIn('三月的狮子_ABC123', path)

    def test_book_path(self):
        path = get_output_path('/export', '三月的狮子', 'ABC123',
                               '第1卷', 'DEF456')
        self.assertIn('三月的狮子_ABC123', path)
        self.assertIn('第1卷_DEF456', path)

    def test_special_chars_sanitized(self):
        path = get_output_path('/export', 'a:b/c', 'ID1', 'v<1>', 'ID2')
        self.assertNotIn(':', path)
        self.assertNotIn('<', path)
        self.assertNotIn('>', path)


if __name__ == '__main__':
    unittest.main()
