name: Unittest CI

on:
  # 没啥必要
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Python Version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Requirements And Test-only Package
        run: |
          pip install -r install/requirements.txt
          pip install coverage
          
      # 便于测试代码导入config.config
      - name: Copy config.template.py to config.py
        run: cp config/config.template.py config/config.py

      - name: Run Unittest
        # 强制返回 0 避免流水线中断
        run: |
          python run_unittests.py || exit 0  
        continue-on-error: true

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: 测试结果报告
          path: test_results/